version: '3.9'

services:
  web:
    build: .
    container_name: fastapi_backend
    volumes: 
      - .:/code/
    ports: 
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

    
  db:
      image: postgres:13.4
      container_name: fastapi_db
      ports:
        - "5432:5432"
      env_file:
        - .env
      
