version: '3.9'

services: 
  db:
    image: postgres:14.4
    container_name: fastapi_db
    env_file:
      - .env
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
  
  web:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    container_name: fastapi_backend
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes: 
      - .:/code
    depends_on:
      - db

volumes:
  postgres_data: