version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    container_name: fastapi_backend
    volumes: 
      - .:/code/
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
      
  db:
    image: postgres:14.4
    container_name: fastapi_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d

volumes:
  postgres_data: