version: '3.9'

services:
  db:
      image: postgres:13.4
      container_name: fastapi_db
      env_file:
        - .env
      volumes:
        - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: fastapi_backend
    volumes: 
      - .:/code/
    env_file:
      - .env
    depends_on:
      - db
    restart: always
      
volumes:
  postgres_data: