"""empty message

Revision ID: 031ac250806c
Revises: 0def45b00aa5
Create Date: 2024-03-25 19:56:49.993957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031ac250806c'
down_revision = '0def45b00aa5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
