"""empty message

Revision ID: 0b68cdb2c8bc
Revises: ae8b6e66bfc6
Create Date: 2023-11-13 11:55:16.560188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b68cdb2c8bc'
down_revision = 'ae8b6e66bfc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
