"""empty message

Revision ID: 0caa8ea45893
Revises: 7ee5ea7db88a
Create Date: 2023-03-18 20:42:40.781173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0caa8ea45893'
down_revision = '7ee5ea7db88a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('association_table_product_id_fkey', 'association_table', type_='foreignkey')
    op.drop_constraint('association_table_category_id_fkey', 'association_table', type_='foreignkey')
    op.create_foreign_key(None, 'association_table', 'category', ['category_id'], ['id'], onupdate='cascade', ondelete='cascade')
    op.create_foreign_key(None, 'association_table', 'product', ['product_id'], ['id'], onupdate='cascade', ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'association_table', type_='foreignkey')
    op.drop_constraint(None, 'association_table', type_='foreignkey')
    op.create_foreign_key('association_table_category_id_fkey', 'association_table', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('association_table_product_id_fkey', 'association_table', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
