"""empty message

Revision ID: 39a943cc84b6
Revises: f01b5ada04c4
Create Date: 2023-01-27 12:56:21.108356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39a943cc84b6'
down_revision = 'f01b5ada04c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_table',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], )
    )
    op.create_unique_constraint(None, 'category', ['id'])
    op.create_unique_constraint(None, 'product', ['id'])
    op.drop_constraint('product_category_id_fkey', 'product', type_='foreignkey')
    op.drop_column('product', 'category_id')
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.add_column('product', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('product_category_id_fkey', 'product', 'category', ['category_id'], ['id'])
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_table('association_table')
    # ### end Alembic commands ###
