"""empty message

Revision ID: 587d180ff1a8
Revises: d70557624e06
Create Date: 2023-04-27 12:53:37.732325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "587d180ff1a8"
down_revision = "d70557624e06"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "association_table", "category_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "association_table", "product_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "association_table", "product_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "association_table", "category_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
