"""empty message

Revision ID: 635411e24a95
Revises: aa4e832105be
Create Date: 2023-07-13 14:15:40.037998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635411e24a95'
down_revision = 'aa4e832105be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'category', ['id'])
    op.create_unique_constraint(None, 'order', ['id'])
    op.create_unique_constraint(None, 'product', ['id'])
    op.add_column('user', sa.Column('is_superuser', sa.Boolean(), server_default='false', nullable=False))
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'is_superuser')
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_constraint(None, 'order', type_='unique')
    op.drop_constraint(None, 'category', type_='unique')
    # ### end Alembic commands ###
