"""empty message

Revision ID: 6e80578b9139
Revises: 587d180ff1a8
Create Date: 2023-05-14 09:13:14.132951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e80578b9139'
down_revision = '587d180ff1a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
