"""empty message

Revision ID: 83cce3b6f8b9
Revises: 76e48932b0f2
Create Date: 2023-02-21 13:59:24.640116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83cce3b6f8b9'
down_revision = '76e48932b0f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('association_table_category_id_fkey', 'association_table', type_='foreignkey')
    op.drop_constraint('association_table_product_id_fkey', 'association_table', type_='foreignkey')
    op.create_foreign_key(None, 'association_table', 'category', ['category_id'], ['id'], onupdate='cascade', ondelete='cascade')
    op.create_foreign_key(None, 'association_table', 'product', ['product_id'], ['id'], onupdate='cascade', ondelete='cascade')
    op.create_unique_constraint(None, 'category', ['id'])
    op.create_unique_constraint(None, 'product', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_constraint(None, 'association_table', type_='foreignkey')
    op.drop_constraint(None, 'association_table', type_='foreignkey')
    op.create_foreign_key('association_table_product_id_fkey', 'association_table', 'product', ['product_id'], ['id'])
    op.create_foreign_key('association_table_category_id_fkey', 'association_table', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###
