"""empty message

Revision ID: 8b4a8ba5fc81
Revises: 41d7e04e3138
Create Date: 2023-06-02 16:10:08.944205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b4a8ba5fc81'
down_revision = '41d7e04e3138'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'category', ['id'])
    op.create_unique_constraint(None, 'order', ['id'])
    op.drop_constraint('order_user_id_fkey', 'order', type_='foreignkey')
    op.drop_column('order', 'user_id')
    op.create_unique_constraint(None, 'product', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'product', type_='unique')
    op.add_column('order', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('order_user_id_fkey', 'order', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'order', type_='unique')
    op.drop_constraint(None, 'category', type_='unique')
    # ### end Alembic commands ###
