"""empty message

Revision ID: 9c1e4e6011a7
Revises: 
Create Date: 2024-02-20 14:00:31.867898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c1e4e6011a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('cart_total_price', sa.Float(), nullable=False))
    op.create_unique_constraint(None, 'cart', ['id'])
    op.add_column('cart_item', sa.Column('cart_item_price', sa.Float(), nullable=False))
    op.create_unique_constraint(None, 'cart_item', ['id'])
    op.create_unique_constraint(None, 'category', ['id'])
    op.add_column('order', sa.Column('waiting_for_payment', sa.Boolean(), server_default='true', nullable=False))
    op.create_unique_constraint(None, 'order', ['id'])
    op.add_column('order_item', sa.Column('order_item_price', sa.Float(), nullable=False))
    op.create_unique_constraint(None, 'order_item', ['id'])
    op.create_unique_constraint(None, 'product', ['id'])
    op.create_unique_constraint(None, 'product_inventory', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'user_address', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_address', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'product_inventory', type_='unique')
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_constraint(None, 'order_item', type_='unique')
    op.drop_column('order_item', 'order_item_price')
    op.drop_constraint(None, 'order', type_='unique')
    op.drop_column('order', 'waiting_for_payment')
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_constraint(None, 'cart_item', type_='unique')
    op.drop_column('cart_item', 'cart_item_price')
    op.drop_constraint(None, 'cart', type_='unique')
    op.drop_column('cart', 'cart_total_price')
    # ### end Alembic commands ###
