"""empty message

Revision ID: cc0e793dfb25
Revises: efae3aa069ee
Create Date: 2024-04-07 08:40:28.233362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc0e793dfb25'
down_revision = 'efae3aa069ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cart', ['id'])
    op.create_unique_constraint(None, 'cart_item', ['id'])
    op.create_unique_constraint(None, 'category', ['id'])
    op.add_column('order', sa.Column('cancelled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('order', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('order', sa.Column('payment_deadline', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'order', ['id'])
    op.create_unique_constraint(None, 'order_item', ['id'])
    op.create_unique_constraint(None, 'product', ['id'])
    op.create_unique_constraint(None, 'product_inventory', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'user_address', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_address', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'product_inventory', type_='unique')
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_constraint(None, 'order_item', type_='unique')
    op.drop_constraint(None, 'order', type_='unique')
    op.drop_column('order', 'payment_deadline')
    op.drop_column('order', 'created_at')
    op.drop_column('order', 'cancelled')
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_constraint(None, 'cart_item', type_='unique')
    op.drop_constraint(None, 'cart', type_='unique')
    # ### end Alembic commands ###
