"""empty message

Revision ID: cd10271cdda3
Revises: d973386e46fa
Create Date: 2024-03-29 20:01:02.598639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd10271cdda3'
down_revision = 'd973386e46fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
