"""empty message

Revision ID: d70557624e06
Revises: 123bb24989ec
Create Date: 2023-04-18 18:55:38.460379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d70557624e06"
down_revision = "123bb24989ec"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "category", ["id"])
    op.create_unique_constraint(None, "category", ["name"])
    op.create_unique_constraint(None, "product", ["name"])
    op.create_unique_constraint(None, "product", ["id"])
    op.create_unique_constraint(None, "user", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_constraint(None, "product", type_="unique")
    op.drop_constraint(None, "product", type_="unique")
    op.drop_constraint(None, "category", type_="unique")
    op.drop_constraint(None, "category", type_="unique")
    # ### end Alembic commands ###
