"""empty message

Revision ID: d973386e46fa
Revises: e65a0a6b10a0
Create Date: 2024-03-28 20:00:57.416862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd973386e46fa'
down_revision = 'e65a0a6b10a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('total_order_price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'total_order_price')
    # ### end Alembic commands ###
