"""empty message

Revision ID: ee481e216246
Revises: 873e7cedb671
Create Date: 2024-04-10 17:12:30.877760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee481e216246'
down_revision = '873e7cedb671'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cart', ['id'])
    op.create_unique_constraint(None, 'cart_item', ['id'])
    op.create_unique_constraint(None, 'category', ['id'])
    op.alter_column('category_product_association_table', 'category_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'order', ['id'])
    op.create_unique_constraint(None, 'order_item', ['id'])
    op.create_unique_constraint(None, 'product', ['id'])
    op.create_unique_constraint(None, 'product_inventory', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'user_address', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_address', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'product_inventory', type_='unique')
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_constraint(None, 'order_item', type_='unique')
    op.drop_constraint(None, 'order', type_='unique')
    op.alter_column('category_product_association_table', 'category_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_constraint(None, 'cart_item', type_='unique')
    op.drop_constraint(None, 'cart', type_='unique')
    # ### end Alembic commands ###
